#!/usr/bin/env sh

# Check if it's a merge
git merge HEAD &> /dev/null

IS_MERGE_PROCESS=$?

if [ $IS_MERGE_PROCESS -ne 0 ];
  then
    exit $?
  fi

# Get staged files
STAGED_FILES=$(git diff --cached --name-only)

# Abort if staging area is empty
if [[ "$STAGED_FILES" = "" ]];
  then
    exit 0
  fi

echo "🔍 Running pre-commit checks..."

# Format code with Prettier
echo "💅 Formatting code..."
npm run format

git add $STAGED_FILES

echo "✅ Pre-commit checks completed!"